apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "tech-radar.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.backend.name }}
    app.kubernetes.io/component: {{ .Values.backend.component }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.backend.name }}
        app.kubernetes.io/component: {{ .Values.backend.component }}
    spec:
      containers:
        - name: api
          image: {{ include "tech-radar.backendImage" . }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: teknoloji-config
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: teknoloji-secret
                  key: SECRET_KEY
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: teknoloji-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: teknoloji-secret
                  key: DB_PASSWORD
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.probes.readiness.path }}
              port: {{ .Values.backend.port }}
            initialDelaySeconds: {{ .Values.backend.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.probes.readiness.timeoutSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.probes.liveness.path }}
              port: {{ .Values.backend.port }}
            initialDelaySeconds: {{ .Values.backend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.probes.liveness.timeoutSeconds }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "tech-radar.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.backend.name }}
    app.kubernetes.io/component: {{ .Values.backend.component }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
  selector:
    app.kubernetes.io/name: {{ .Values.backend.name }}
