apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    {{- include "tech-radar.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.global.appName }}
