apiVersion: v1
kind: Secret
metadata:
  name: teknoloji-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "tech-radar.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  DB_USER: {{ .Values.secrets.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
