# Generated by Django 4.2.7 on 2026-09-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_ainewsentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='ainewsentry',
            name='needs_translation',
            field=models.BooleanField(default=False, verbose_name='Ceviri Bekliyor'),
        ),
        migrations.AddField(
            model_name='cveentry',
            name='needs_translation',
            field=models.BooleanField(default=False, verbose_name='Ceviri Bekliyor'),
        ),
        migrations.AddField(
            model_name='devtoolsentry',
            name='needs_translation',
            field=models.BooleanField(default=False, verbose_name='Ceviri Bekliyor'),
        ),
        migrations.AddField(
            model_name='kubernetesentry',
            name='needs_translation',
            field=models.BooleanField(default=False, verbose_name='Ceviri Bekliyor'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='needs_translation',
            field=models.BooleanField(default=False, verbose_name='Ceviri Bekliyor'),
        ),
        migrations.AddField(
            model_name='sreentry',
            name='needs_translation',
            field=models.BooleanField(default=False, verbose_name='Ceviri Bekliyor'),
        ),
    ]
