# Generated by Django 4.2.7 on 2026-09-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_needs_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ainewsentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Guncellenme Tarihi'),
        ),
        migrations.AddField(
            model_name='cveentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Guncellenme Tarihi'),
        ),
        migrations.AddField(
            model_name='devtoolsentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Guncellenme Tarihi'),
        ),
        migrations.AddField(
            model_name='kubernetesentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Guncellenme Tarihi'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Guncellenme Tarihi'),
        ),
        migrations.AddField(
            model_name='sreentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Guncellenme Tarihi'),
        ),
        migrations.AddIndex(
            model_name='ainewsentry',
            index=models.Index(fields=['updated_at', 'id'], name='news_ainews_updated_b7b611_idx'),
        ),
        migrations.AddIndex(
            model_name='cveentry',
            index=models.Index(fields=['updated_at', 'id'], name='news_cveent_updated_bfc82f_idx'),
        ),
        migrations.AddIndex(
            model_name='devtoolsentry',
            index=models.Index(fields=['updated_at', 'id'], name='news_devtoo_updated_6a625c_idx'),
        ),
        migrations.AddIndex(
            model_name='kubernetesentry',
            index=models.Index(fields=['updated_at', 'id'], name='news_kubern_updated_aeebb1_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['updated_at', 'id'], name='news_newsar_updated_488b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='sreentry',
            index=models.Index(fields=['updated_at', 'id'], name='news_sreent_updated_2eefc3_idx'),
        ),
    ]
