# Generated by Django 4.2.7 on 2026-09-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_translation_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ainewsentry',
            name='translation_provider',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('libretranslate', 'LibreTranslate'), ('gemini', 'Gemini')], default='', max_length=20, verbose_name='Ceviri Saglayicisi'),
        ),
        migrations.AlterField(
            model_name='cveentry',
            name='translation_provider',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('libretranslate', 'LibreTranslate'), ('gemini', 'Gemini')], default='', max_length=20, verbose_name='Ceviri Saglayicisi'),
        ),
        migrations.AlterField(
            model_name='devtoolsentry',
            name='translation_provider',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('libretranslate', 'LibreTranslate'), ('gemini', 'Gemini')], default='', max_length=20, verbose_name='Ceviri Saglayicisi'),
        ),
        migrations.AlterField(
            model_name='kubernetesentry',
            name='translation_provider',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('libretranslate', 'LibreTranslate'), ('gemini', 'Gemini')], default='', max_length=20, verbose_name='Ceviri Saglayicisi'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='translation_provider',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('libretranslate', 'LibreTranslate'), ('gemini', 'Gemini')], default='', max_length=20, verbose_name='Ceviri Saglayicisi'),
        ),
        migrations.AlterField(
            model_name='sreentry',
            name='translation_provider',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('libretranslate', 'LibreTranslate'), ('gemini', 'Gemini')], default='', max_length=20, verbose_name='Ceviri Saglayicisi'),
        ),
    ]
