# Generated by Django 4.2.7 on 2026-09-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_translation_provider_gemini'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('cve', 'CVE'), ('news', 'Haber'), ('kubernetes', 'Kubernetes'), ('sre', 'SRE'), ('devtools', 'DevTools'), ('ai', 'Yapay Zeka'), ('retranslate', 'Yeniden Ceviri')], db_index=True, max_length=20, verbose_name='Bolum')),
                ('trigger', models.CharField(choices=[('beat', 'Zamanlayici'), ('api', 'API'), ('admin', 'Arayuz')], default='beat', max_length=10, verbose_name='Tetikleyici')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Baslangic')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitis')),
                ('status', models.CharField(choices=[('running', 'Calisiyor'), ('success', 'Basarili'), ('failure', 'Basarisiz')], default='running', max_length=10, verbose_name='Durum')),
                ('fetched_count', models.IntegerField(default=0, verbose_name='Kaynaktan Gelen')),
                ('saved_count', models.IntegerField(default=0, verbose_name='Yazilan')),
                ('translation_failures', models.IntegerField(default=0, verbose_name='Ceviri Hatasi')),
                ('total_after', models.IntegerField(default=0, verbose_name='Tur Sonu Toplam')),
                ('by_provider', models.JSONField(blank=True, default=dict, verbose_name='Saglayici Dagilimi')),
                ('stopped_reason', models.CharField(blank=True, default='', max_length=30, verbose_name='Durma Sebebi')),
                ('error', models.TextField(blank=True, default='', verbose_name='Hata')),
            ],
            options={
                'verbose_name': 'Cekim Kaydi',
                'verbose_name_plural': 'Cekim Kayitlari',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['section', '-started_at'], name='news_fetchr_section_78c0ff_idx')],
            },
        ),
    ]
