# Generated by Django 4.2.30 on 2026-09-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_fetchrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='link',
            field=models.URLField(unique=True, verbose_name='Link'),
        ),
    ]
